#:schema https://raw.githubusercontent.com/jiwonz/pesde-schema/refs/heads/0.5/schema/generated/pesde.json
name = "caveful_games/handynet"
version = "0.3.0"
description = "ByteNet fork made more handy"
authors = ["ffrostfall", "jiwonz"]
repository = "https://github.com/CavefulGames/HandyNet"
license = "MIT"
includes = ["src", "README.md", "LICENSE.md", "pesde.toml"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
limesignal = { name = "caveful_games/limesignal", version = "^0.1.10" }
